config/routes.rb
Rails.application.routes.draw do
  get 'tweet/analyze'

  get 'tweet/show'

  # ===
  # Root
  # ===
  root 'static_pages#index'

  resources :hashtags, only: [:index, :new, :create, :show] do
    member do
      post 'sync_tweets'
      post 'analyze_tweets'
      get 'tweets'
    end
  end

  resources :tweets, only: [:show] do
    member do
      post 'analyze'
    end
  end
end

app/models/hashtag.rb
class Hashtag
  include Mongoid::Document

  # ===
  # Fields
  # ===
  field :hashtag, type: String

  # ===
  # Associations
  # ===
  has_many :tweets

  # ===
  # Methods
  # ===
  def has_tweet?(twitter_id)
    self.tweets.where(twitter_id: twitter_id).count > 0
  end

  def save_tweet(tweet)
    tweet = self.tweets.build text: tweet.full_text,
                              twitter_id: tweet.id.to_s,
                              url: tweet.url.to_s,
                              author_id: tweet.user.id.to_s

    tweet.save
  end

  def tweet_with_id(twitter_id)
    self.tweets.where(twitter_id: twitter_id).first
  end

  def un_analyzed_tweets
    self.tweets.where(analyzed: false)
  end

  def has_tweets_for_analysis?
    self.tweets.where(analyzed: false).count > 0
  end

  def google_charts_json
    sentiment_dictionary = {}

    self.tweets.each do |tweet|
      # Value is an array: first element is the amount of tweets with that sentiment, second is the sum of it's scores
      if tweet.sentiment
        if sentiment_dictionary.has_key? tweet.sentiment.type
          sentiment_dictionary[tweet.sentiment.type] = [
              sentiment_dictionary[tweet.sentiment.type].first + 1,
              sentiment_dictionary[tweet.sentiment.type].last + tweet.sentiment.score.to_f
          ]
        else
          sentiment_dictionary[tweet.sentiment.type] = [0, tweet.sentiment.score.to_f]
        end
      end
    end

    data = sentiment_dictionary.collect do |key, value|
      ["#{key} (#{value.last / value.first})", value.first] if value.first != 0
    end

    data.compact.unshift(['Sentiment', 'Amount of tweets']).to_json
  end
end

app/models/sentiment.rb
class Sentiment
  include Mongoid::Document

  # ===
  # Fields
  # ===
  field :type, type: String
  field :score, type: String
  field :mixed, type: String

  # ===
  # Associations
  # ===
  embedded_in :tweet
end

app/models/taxonomy.rb
class Taxonomy
  include Mongoid::Document

  # ===
  # Fields
  # ===
  field :confident, type: String
  field :label, type: String
  field :score, type: String

  # ===
  # Associations
  # ===
  embedded_in :tweet
end

app/models/tweet.rb
class Tweet
  include Mongoid::Document

  # ===
  # Fields
  # ===
  field :text, type: String
  field :twitter_id, type: String
  field :url, type: String
  field :author_id, type: String
  field :analyzed, type: Mongoid::Boolean, default: false

  # ===
  # Associations
  # ===
  belongs_to :hashtag
  embeds_one :sentiment
  embeds_many :taxonomies

  # ===
  # Methods
  # ===
  def marked_as_analyzed
    self.analyzed = true
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  include TwitterClientHelper, AlchemyHelper

  before_action :set_hashtag, only: [:show, :sync_tweets, :tweets, :analyze_tweets]

  # ===
  # Actions
  # ===
  def index
    @hashtags = Hashtag.all
  end

  def new
    @hashtag = Hashtag.new
  end

  def create
    @hashtag = Hashtag.new(hashtag_params)

    respond_to do |format|
      if @hashtag.save
        format.html { redirect_to hashtags_path, notice: 'Hashtag was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
  end

  def sync_tweets
    tweets = get_tweets_for_hashtag(@hashtag.hashtag)
    tweets.each do |tweet|
      unless @hashtag.has_tweet? tweet.id.to_s
        @hashtag.save_tweet tweet
      end
    end

    redirect_to tweets_hashtag_path(@hashtag)
  end

  def analyze_tweets
    @hashtag.un_analyzed_tweets.each do |tweet|
      analyze_tweet tweet
    end

    redirect_to tweets_hashtag_path @hashtag
  end

  def tweets
    @tweets = @hashtag.tweets
  end

  private
  def set_hashtag
    @hashtag = Hashtag.find(params[:id])
  end

  def hashtag_params
    params.require(:hashtag).permit(:hashtag)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  # ===
  # Actions
  # ===
  def index
    redirect_to hashtags_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include AlchemyHelper

  before_action :set_tweet

  # ===
  # Actions
  # ===
  def analyze
    analyze_tweet @tweet
    redirect_to @tweet
  end

  def show
  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/alchemy_helper.rb
module AlchemyHelper
  def analyze_tweet(tweet)
    get_sentiment_for_tweet tweet
    get_taxonomies_for_tweet tweet

    tweet.marked_as_analyzed
  end

  private
  def get_sentiment_for_tweet(tweet)
    url = get_alchemy_query_url(tweet.text, 'text/TextGetTextSentiment')
    response = RestClient.get url, { content_type: :json, accept: :json }
    json_response = JSON.parse response.body

    tweet.create_sentiment json_response['docSentiment'] if json_response['docSentiment']
  end

  def get_taxonomies_for_tweet(tweet)
    url = get_alchemy_query_url(tweet.text, 'text/TextGetRankedTaxonomy')
    response = RestClient.get url, { content_type: :json, accept: :json }
    json_response = JSON.parse response.body

    if json_response['taxonomy']
      json_response['taxonomy'].each do |taxonomy|
        tweet.taxonomies.create taxonomy
      end
    end
  end

  def get_alchemy_query_url(text, alchemy_resource)
    encoded_text = URI.encode text
    "#{ENV['ALCHEMY_URL']}/#{alchemy_resource}?apikey=#{ENV['ALCHEMY_API_KEY']}&outputMode=json&text=#{encoded_text}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def twitter_hashtag_url(hashtag)
    "https://twitter.com/search?q=%23#{hashtag.hashtag}"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def alert_class(flash_key)
    case flash_key
      when 'notice'
        'alert-success'
      when 'alert'
        'alert-warning'
      when 'warning'
        'alert-warning'
      when 'error'
        'alert-danger'
      when 'success'
        'alert-success'
      else
        'alert-info'
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/twitter_client_helper.rb
module TwitterClientHelper
  def get_tweets_for_hashtag(hashtag)
    twitter_client.search("##{hashtag} -rt")
  end

  private
  def twitter_client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['CONSUMER_KEY']
      config.consumer_secret     = ENV['CONSUMER_SECRET']
      config.access_token        = ENV['TOKEN']
      config.access_token_secret = ENV['TOKEN_SECRET']
    end
  end
end

app/views/hashtags/_form.html.erb
<%= form_for(@hashtag, html: { class: 'generic-form' }) do |f| %>

    <div class="form-group">
      <%= f.label :hashtag %><br>
      <div class="input-group">
        <div class="input-group-addon">#</div>
        <%= f.text_field :hashtag %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit %>
    </div>
<% end %>

app/views/hashtags/index.html.erb
<h1>Listing Hashtags</h1>

<table class="table">
  <thead>
  <tr>
    <th>Hashtag</th>
    <th>Amount of tweets</th>
    <th>Amount of tweets without analysis</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @hashtags.each do |hashtag| %>
      <tr>
        <td><%= link_to "##{hashtag.hashtag}", twitter_hashtag_url(hashtag), target: :blank %></td>
        <td><%= hashtag.tweets.count %></td>
        <td><%= hashtag.un_analyzed_tweets.count %></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Actions <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to 'See tweets', tweets_hashtag_path(hashtag) %></li>
              <% if hashtag.has_tweets_for_analysis? %>
                  <li><%= link_to 'Analyze all tweets', analyze_tweets_hashtag_path(hashtag), method: :post, class: 'show-overlay-btn' %></li>
              <% else %>
                  <li><%= link_to 'See statistics', hashtag %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sync tweets', sync_tweets_hashtag_path(hashtag), method: :post, class: 'show-overlay-btn' %></li>
            </ul>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hashtag', new_hashtag_path %>

<script>
  $(".show-overlay-btn").click(function() {
    $(".working-overlay").show();
  });
</script>

app/views/hashtags/new.html.erb
<h1>New Hashtag</h1>

<%= render 'form' %>

<%= link_to 'Back', hashtags_path %>

app/views/hashtags/show.html.erb
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<h1 class="text-center"><%= link_to "##{@hashtag.hashtag}", twitter_hashtag_url(@hashtag), target: :blank %></h1>

<div id="sentiment-chart" style="width: 900px; height: 500px;"></div>

<script>
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);
  function drawChart() {

    var data = google.visualization.arrayToDataTable(<%= raw @hashtag.google_charts_json %>);

    var options = {
      title: 'Sentiment'
    };

    var chart = new google.visualization.PieChart(document.getElementById('sentiment-chart'));

    chart.draw(data, options);
  }
</script>

app/views/hashtags/tweets.html.erb
<h1>Listing Tweets</h1>

<table class="table">
  <thead>
  <tr>
    <th>Text</th>
    <th>Analyzed?</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.text %></td>
        <td><%= tweet.analyzed ? 'Yes' : 'No' %></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Actions <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <% if tweet.analyzed %>
                  <li><%= link_to 'See analysis', tweet %></li>
              <% else %>
                  <li><%= link_to 'Analyzed tweet', analyze_tweet_path(tweet), method: :post %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'See in Twitter', tweet.url, target: :blank %></li>
            </ul>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', :back %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">EAFIT - SITI 2016</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Hashtags', hashtags_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taller EAFIT</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= render partial: 'shared/flash', locals: { flash: flash } %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= yield %>
    </div>
  </div>
</div>

<%= render 'shared/working_overlay' %>

</body>
</html>

app/views/shared/_flash.html.erb
<% unless flash.empty? %>
    <div class="container static-flash">
      <div class="flash-container">
        <% flash.each do |key, value| %>
            <% bt = button_tag('x', type: 'button', class: 'close', 'data-dismiss' => 'alert') %>
            <%= content_tag(:div, bt + raw(value), class: "alert #{alert_class(key)}") %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/shared/_working_overlay.html.erb
<div class="working-overlay">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
        <div class="message-container">
          <div class="message text-center">
            <h2>Working</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/tweets/show.html.erb
<h2 class="text-center"><%= @tweet.text %></h2>

<% if @tweet.sentiment %>
    <p class="lead">Sentiment:</p>
    <ul>
      <li>Type: <%= @tweet.sentiment.type %></li>
      <li>Score: <%= @tweet.sentiment.score.to_s.blank? ? 'N/A' : @tweet.sentiment.score %></li>
      <li>Mixed: <%= @tweet.sentiment.mixed.to_s.blank? ? 'N/A' : @tweet.sentiment.mixed %></li>
    </ul>
<% end %>

<% unless @tweet.taxonomies.empty? %>
    <br/>
    <p class="lead">Taxonomies:</p>
    <% @tweet.taxonomies.each do |taxonomy| %>
        <ul>
          <li>Confident: <%= taxonomy.confident.to_s.blank? ? 'N/A' :taxonomy.confident %></li>
          <li>Label: <%= taxonomy.label.to_s.blank? ? 'N/A' :taxonomy.label %></li>
          <li>Score: <%= taxonomy.score.to_s.blank? ? 'N/A' :taxonomy.score %></li>
        </ul>
    <% end %>
<% end %>

<%= link_to 'Back', :back %>